# Generated by Django 3.2.6 on 2022-02-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(choices=[('opensea', 'OpenSea'), ('nifty_gateway', 'Nifty Gateway'), ('rarible', 'Rarible'), ('binance_nft', 'Binance NFT'), ('superrare', 'SuperRare'), ('async_art', 'Async Art')], default='opensea', max_length=100)),
            ],
        ),
    ]
